package net.peakgames.ginrummyplu;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.peakgames.ginrummyplu.ADBEntity;
import net.peakgames.ginrummyplu.FinalUrlEntity;

import net.peakgames.ginrummyplu.ADBEntityDao;
import net.peakgames.ginrummyplu.FinalUrlEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aDBEntityDaoConfig;
    private final DaoConfig finalUrlEntityDaoConfig;

    private final ADBEntityDao aDBEntityDao;
    private final FinalUrlEntityDao finalUrlEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aDBEntityDaoConfig = daoConfigMap.get(ADBEntityDao.class).clone();
        aDBEntityDaoConfig.initIdentityScope(type);

        finalUrlEntityDaoConfig = daoConfigMap.get(FinalUrlEntityDao.class).clone();
        finalUrlEntityDaoConfig.initIdentityScope(type);

        aDBEntityDao = new ADBEntityDao(aDBEntityDaoConfig, this);
        finalUrlEntityDao = new FinalUrlEntityDao(finalUrlEntityDaoConfig, this);

        registerDao(ADBEntity.class, aDBEntityDao);
        registerDao(FinalUrlEntity.class, finalUrlEntityDao);
    }
    
    public void clear() {
        aDBEntityDaoConfig.clearIdentityScope();
        finalUrlEntityDaoConfig.clearIdentityScope();
    }

    public ADBEntityDao getADBEntityDao() {
        return aDBEntityDao;
    }

    public FinalUrlEntityDao getFinalUrlEntityDao() {
        return finalUrlEntityDao;
    }

}
